### ISSUE TITLE
./configure should have +x bit set

### ISSUE THREAD

**Issue by lebigot** [bnordli/rftg#1]
In order to install and do ./configure, the src/configure file should have its +x bit set for the user. It doesn't (at least when cloning on OS X).

**Comment by bnordli** [comment]
Will 4d83e00 suffice?

If there is anything else missing for building on OS X, I'll be happy to take a pull request.

**Comment by lebigot** [comment]
Yeah, I am not yet sure about how to compile on OS X: it is not finding GTK. I haven't investigated this.

**Comment by bnordli** [comment]
This a very old post: https://boardgamegeek.com/article/3875973#3875973,
but MacPorts seems to still be alive, so you can give it a shot.

14. aug. 2016 17:14 skrev "Eric O. LEBIGOT (EOL)" <notifications@github.com

**Comment by lebigot** [comment]
Thanks for the tip! MacPorts is alive and well. :) However, a few things have changed since this post, and I still can't compile despite trying a few things. I'll live with the 0.9.4 binary until I really need the 0.9.4p/q version. :)
