### ISSUE TITLE
Indication of military power during Rebel Alliance takeover is wrong

### ISSUE THREAD

**Issue by Marsux** [bnordli/rftg#10]
The engine computes the correct military power, but the UI count does not take into account the bonus provided by active military world. The issue occured during a network game, I couldn't make a save.

**Comment by bnordli** [comment]
A little more details would be helpful. Is it the mouseover on the attacked card, or the mouseover on the attacker's military strength icon? What is missing/wrong?

**Comment by Marsux** [comment]
Unable to reproduce the issue on the latest version.

**Comment by bnordli** [comment]
Probably seen on the official 0.9.4. This was fixed in 0.9.4p.
