### ISSUE TITLE
Prestige UI Symbol Does Not Visibly Indicate Whether Prestige/Search Action Available

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#11]
I noticed this while streaming. The information in the topic is only visible in a hidden popup hover. This is vital game state information that should be statically indicated at all times. I can't think of any other game-critical information that isn't immediately visible.

Options include half-greying out the symbol; or putting a little green checkmark/red X on it somewhere to indicate status; or a mini-card symbol of the prestige action, colored when available, and grey once used.

**Comment by Marsux** [comment]
The prestige selection button is only visible when the prestige/search action is usable. Would it be ok to make it visible only when the prestige search action is available, greying it out if the action is not usable (no prestige).

**Comment by dsnvwlmnt** [comment]
That's only during action selection, and only for the local player. While that would be a small improvement, it doesn't solve the real problem, which is seeing the prestige/search status of all players at all times. I'd just modify the prestige point indicator circle in some way probably.

**Comment by bnordli** [comment]
Does this look OK? I have added a red cross when the Prestige/Search action is used (blue player), and a * to the count when prestige is on the tile (red player). There are no changes to the tool tips.

![prestige](https://cloud.githubusercontent.com/assets/5574761/20385875/82a319fe-acb9-11e6-96ef-5f467a907bae.png)

**Comment by dsnvwlmnt** [comment]
Yeah that should do the trick. Could probably thicken the red x slightly or give it a white outline so it stands out against the similar purple color.

**Comment by piperjackson** [comment]
In the javascript implementation, the Prestige marker is greyed out after using the special action. This makes it very easy to check the current status of all players and works very well.

**Comment by dsnvwlmnt** [comment]
Piper, can you post a screenshot? Without seeing it, greying out the purple prestige symbol seems less 
than ideal since the loss of purpleness might be confusing to less experienced players. "Where'd my prestige go?". Also, how does the javascript version indicate prestige on the tile?

**Comment by bnordli** [comment]
@piperjackson Thanks for the input! That sounds like a better idea. I was worried too about the missing purple, but there will still be some color left in the symbol, like this: 
![prestige2](https://cloud.githubusercontent.com/assets/5574761/20422301/dedd1444-ad69-11e6-85dc-7f1c15684a15.png)

@Marsux What did you mean about the '*' character? Difficult to understand in general, or in combination with the cross? There's always the tool tip, if anyone would like to know what the symbol means.

**Comment by Marsux** [comment]
We could also have a square pink symbol, with either a ">" character of "=" character, and a prestige token image if there is prestige is on the > tile.

For the availability of the prestige search action, there is a prestige/? image that could be used, and be present as long as it is available.

**Comment by dsnvwlmnt** [comment]
Yeah you could use the actual game assets instead of create new things for people to learn.

Prestige tile, showing whichever of the two sides is relevant. = side up, or > side up with/without a prestige on the tile.

Mini-Prestige/Search action card, grey if used.

**Comment by bnordli** [comment]
I am sorry, but bringing new assets into the code for previous expansions is out of scope. We have to work with what we have. A pink square won't look good, and even the action cards will be super-mini and still take up space in the already crowded status bar. I am fairly confident about the greying out. Could be convinced otherwise about the *. Should I just drop it?

**Comment by dsnvwlmnt** [comment]
That's fair. I definitely would like some indication of prestige on the tile, rather than no immediately visible indication. Asterisk if we don't have anything better.

**Comment by bnordli** [comment]
Sample implementation pushed to issue/11-prestige-indicator

**Comment by bnordli** [comment]
..and merged to patch.
