### ISSUE TITLE
Action selection

### ISSUE THREAD

**Issue by Marsux** [bnordli/rftg#13]
Graphical difference between pressed button and nonpressed button is hard to see at first glimpse. It is sometimes problematic when the player hesitates between several choices, ends up with several button pressed and has to try and find those that are pressed and those that aren't.

Would it be possible to accentuate the difference between the pressed and non pressed state of the action choice buttons?

**Comment by dsnvwlmnt** [comment]
This is currently better than it was a certain time in the past, but it's still not perfect, yea. The most recently clicked button also has an odd surrounding highlight that seems unnecessary.

Either the buttons could be a lot more bevelled, or a darker color than the light blue could be used.

**Comment by bnordli** [comment]
We are pretty much stuck with the current skin of gtk, if anyone knows how to easily modify that, I'm open for suggestions.

The highlight box is the tab focus indicator and can be removed by not giving focus to the button when clicked. I'll do that.

**Comment by bnordli** [comment]
After some thought: There is already a 'highlight action' concept as a blue box on the phase overview. I copied that to the action selector also, and after adding 5px to the height, it looks quite reasonable:

![color](https://cloud.githubusercontent.com/assets/5574761/20440322/eb440462-adbf-11e6-9a2f-a229dca1cdc8.png)

For consistency, I also added 5px to each player's status box. Does this look good to you?

**Comment by Marsux** [comment]
This looks much better. A minor remark: if the button is colored blue, the height of the button could probably not be modified by activation. In the example above, the blue squares are not centered.

**Comment by dsnvwlmnt** [comment]
Ideally the blue square outlines would be closer to the edge. Especially for settle, it makes the symbol look a bit strange, not ideal for newer players, in a game so heavily based on symbol cues. Minor issue if it's not possible.

**Comment by bnordli** [comment]
Yes, the buttons doesn't even need to activate now. In fact, the light blue bleeds through the blue border and changes the color slightly, it's noticeably different from the blue border in the phase bar. Also, the icons should be fully inside. I'll take a closer look. 

Related to #20.

**Comment by bnordli** [comment]
Major rewrite of action selection pushed to issue/13-20-action-indicators.
* Using simple buttons (no group or toggle buttons), so image is always centered
* Focus never given to buttons
* Icon fully inside border when selected
* Height of action bar increased
* Impossible to select more than the requested number of actions

This actually made it possible to consolidate the code for normal and advanced game.

![actions](https://cloud.githubusercontent.com/assets/5574761/20458789/c419465a-aeae-11e6-85d8-bfe5bfcf58ca.png)

**Comment by dsnvwlmnt** [comment]
Excellent!

**Comment by dsnvwlmnt** [comment]
This looks really slick now in rc2. One issue though: the spacing above and below the actions/Done are not equal. Above is thicker than below.

http://imgur.com/a/Ym45C

**Comment by bnordli** [comment]
1px added below the buttons. Looks symmetrical now.

**Comment by bnordli** [comment]
BTW, I also added some spacing around the "Done" text.
