### ISSUE TITLE
Military Bug? Seed #1479440838

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#14]
Maybe i'm just tired and not seeing it, but i think i was able to play Alien Monolith for free here when i should have had to pay 2 discards or 1 prestige.

https://www.twitch.tv/unsane/v/101721041?t=116m35s

I have 6 base military. I play AM. The OK button is available to click straight away... I didn't notice that shouldn't be possible because i was playing speed games.

- On develop I play and pay for Space Marines, down to 5 in hand, 2 prestige.
- On settle I play AM and pay 0 (???), down to 4 in hand, draw settle bonus to 5, 3 prestige. (Discarded no cards and spent no Prestige).
- On consume I trade up to 10 cards, 3 prestige. By my count I should be ending the round with 8 cards 3 prestige, or 10 cards 2 prestige.

The game can be replayed using the seed and following what i do starting 2 minutes earlier. BoW 3p Goals on Takeovers Off.

**Comment by bnordli** [comment]
Yes, this is actually a newly introduced bug: the check for extra military on settle_needed now ignores Alien Booby Trap's CONSUME_PRESTIGE flag. @Marsux, can you take a look at this?

Save game:

RFTG Save
0.9.5
1479440838
2 3
1 0 1
none
146 1 0 2 61 109 1 137 0 0 2 3 4 0 5 151 1 151 0 5 -1 0 0 0 0 2 0 3 0 22 0 0 0 23 0 0 0 5 159 2 159 112 0 6 0 2 64 142 0 5 3 2 3 125 0 6 0 0 0 0 0 2 3 4 0 2 0 1 70 0 5 -1 0 0 5 -1 2 146 112 0 0 0 2 5 6 0 5 212 3 212 111 125 0 6 0 0 0 5 224 4 224 111 141 125 0 6 0 0 0 0 0 2 5 7 0 2 0 1 146 0 2 0 1 56 0 5 24 4 24 199 52 112 0 6 0 2 199 52 0 5 141 4 135 111 141 125 0 
152 1 0 2 115 203 1 183 0 0 2 0 3 0 22 1 0 0 23 0 0 0 5 13 1 13 0 5 -1 0 0 0 0 2 5 7 0 5 -1 0 0 5 73 2 73 102 0 12 0 1 73 0 0 0 2 2 9 0 2 0 4 166 67 97 149 0 5 217 4 215 46 217 113 0 6 0 6 116 215 46 219 102 113 0 5 -1 0 0 0 0 2 7 9 0 5 216 3 181 40 216 0 6 0 2 181 205 0 5 40 1 40 0 12 0 1 73 0 0 0 2 2 3 0 2 0 4 188 80 38 204 0 5 150 4 150 86 6 17 0 6 0 5 197 86 6 17 226 0 5 19 1 19 0

**Comment by bnordli** [comment]
Btw, if you enable "Advanced options" ->"Export game when finished", you will automatically get an export of all finished games, which conveniently includes a save game for later replay or debugging.

**Comment by Marsux** [comment]
patch commited, pull request done

**Comment by bnordli** [comment]
Thanks, The fix looks good, I'll take that.
