### ISSUE TITLE
Display Key Cues on the Top Right Corner not Top Left

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#19]
Minor issue but it should be in the top right, because the top left obscures home world numbers. Should be easy to fix.

**Comment by dsnvwlmnt** [comment]
Thinking about this a bit more, this is probably not possible/ideal because cards overlap when you have a lot of them (e.g. Explore+5), and thus the top right corner is hidden.

In that case maybe solely for homeworld selection, you could move it to top right.

**Comment by bnordli** [comment]
Does the home world number really matter? It's always found in the lower right corner, or in the card preview during mouse over.

**Comment by dsnvwlmnt** [comment]
It doesn't matter, it's just bad UI design.
