### ISSUE TITLE
Action Selection: Unselect Previously Clicked Buttons

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#20]
When selecting an action, unselect a previous action. It shouldn't be possible to selection 5 action buttons then have to unclick them all.

Similarly, in 2pe, you should only ever be able to have 2 action buttons selected at any given time. When you click a 3rd, unselect the first action chosen.

**Comment by bnordli** [comment]
In non-advanced, it works exactly like you describe. For advanced, yes,
this could be fixed quite easily.

18. nov. 2016 22:02 skrev "Serge Levert" <notifications@github.com>:

**Comment by bnordli** [comment]
Merging with #13.
