### ISSUE TITLE
Shortcut Keys for Actions are not Streamlined the Way they are for Cards

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#21]
F1 Explore+5
F2 Develop
F3 Settle
F4 Consume: Trade
F5 Produce
F6 Search

**Multiplayer:** No shortcut key for Explore+1 nor Consume x2.

**2pe:** No shortcut key for Explore+1, 2nd Develop, 2nd Settle, Consume x2.

IMO at all times it should be F1-F9 from left to right, not simply always F3 for Settle. Same way the cards in hand work.

You should also display a mini F1-F9 on the action selection buttons. There's no indication of it.

**Comment by bnordli** [comment]
You can get to the short cuts you are missing by using the shift key. (It's
all in the README.)

In this way, the numbers match the phase numbers. (Except the Search, which
is a little clunky.) I am not going to do anything with this.

18. nov. 2016 22:04 skrev "Serge Levert" <notifications@github.com>:

**Comment by dsnvwlmnt** [comment]
Ah sorry about that. Noticed this doesn't work though:

F12:           Open selection drop down

**Comment by dsnvwlmnt** [comment]
One thing i noticed that i think could be an easy improvement here, is to have Spacebar act the same as Enter perhaps? It feels natural to me when i'm using the mouse to save some clicks by using my left thumb that's already sitting on the spacebar. Whereas i'd never move over to Enter unless i was playing on keyboard with 2 hands.

**Comment by bnordli** [comment]
Spacebar would interfere with the chat entry during online games, but I can give you Shift+Spacebar (like Shift+Enter for online games).

**Comment by dsnvwlmnt** [comment]
Hmm why would Spacebar interfere with chat but not Enter?
