### ISSUE TITLE
Revamp Hand Size Number Display During Explore

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#22]
Currently during explore the UI displays all player hand sizes as the total of "hand size" + "cards looking at". This is super unfriendly and we've kind of learned to live with it, but it should definitely not be this way. Just change it to something like "9+8". 9 cards in hand, looking at 8 cards during explore.

**Comment by dsnvwlmnt** [comment]
Even better, you could do 9*8, where * is the eyeball explore symbol.

**Comment by bnordli** [comment]
How would the eye ball fit inside the hand icon? And shouldn't the first count include the non-discarded cards, ie the hand size after explore?

**Comment by dsnvwlmnt** [comment]
How would the eye fit... if a mini-version doesn't fit (or isn't possible without lots of icon work), it doesn't have to be added.

As for counting the explore keep in the hand size, heck no it should not, that would be just as, if not more confusing than the current jumble.

It's in the middle of explore - show the handsize number, and the explore looking at cards number. At least from that some handsizes can be deduced, unlike the status quo 15's and whatnot.

**Comment by bnordli** [comment]
Like this? The icon will only be displayed during the Explore phase.

![bilde](https://cloud.githubusercontent.com/assets/5574761/20928027/37f332ee-bbc4-11e6-8f4f-757d006ad1dc.png)

The tool tip says:
```
Cards drawn: 4
Cards kept: 2
```
Should there be any indicators for players with Mix and Match Explore power?

**Comment by bnordli** [comment]
Tool tip changed to "Cards discarded" instead of "Cards kept". Added * after number for "Mix and Match expore".
