### ISSUE TITLE
Military Influence Goal Doesn't Track Players' Progress (3 Imperium/4 Military World Goal)

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#23]
(This issue pre-dates 0.9.5.)

http://imgur.com/5FBRuFN

RFTG Save
0.9.5
1479504315
2 3
1 0 1
none
71 1 0 2 88 134 1 3 0 0 2 3 5 0 2 0 1 147 0 5 22 1 22 0 5 37 3 106 194 37 0 6 0 0 1 22 0 0 2 7 9 0 12 0 1 37 0 0 0 2 3 7 0 5 128 1 128 0 6 0 5 168 167 170 194 67 0 12 0 1 37 0 
117 1 0 2 225 227 1 180 3 0 4 43 43 193 76 0 0 0 2 1 9 0 2 0 6 157 150 165 89 55 108 0 5 -1 1 214 0 5 193 2 173 193 0 6 0 3 214 173 76 0 3 0 3 173 173 76 0 0 0 2 135 9 0 12 0 1 193 0 13 0 1 -1 1 -1 14 0 2 47 84 0 0 0 2 7 9 0 5 82 6 120 186 191 82 148 43 0 6 0 2 226 43 0 3 0 2 226 43 0 12 0 1 193 0 2 0 1 130 0 
twitch_tv_unsane

**Comment by bnordli** [comment]
The same applies to Peace/War leader. These dual goals are a little hard to track the progress of in a meaningful way.
