### ISSUE TITLE
Differentiate VP Chips from Score

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#25]
Either the VP Chips value or Score value should be colored differently, just so they stand out a bit better from each other. Maybe make the VP Chips number blue.

At the same time you could recolor the VP Pool number, to make it stand out more as well. Currently it's very easy for players to ignore/miss the status of the VP Pool. It's fine currently, but making the # Chips blue to match would probably be an improvement.

**Comment by bnordli** [comment]
I am not changing the color of the VP pool number. The 'Pool' text there should suffice.

Having two colors inside the VP status is a non-trivial change. Also, the chips number is always <= the total VP, and the tool tip will explain the first number, so I don't think this is worth to change.
