### ISSUE TITLE
Refactor expansion data

### ISSUE THREAD

**Issue by bnordli** [bnordli/rftg#27]
(Follow up from #26.)

I would rather see expansion settings in one struct per expansion, to group related information together. expansion_has_goals(exp) should then be replaced with exp_data[exp].has_goals (for instance).

(Using designated initializers, fields set to FALSE can be omitted.)

Information needed per expansion:

* name
* short_name
* max_players
* has_goals
* has_takeovers
* has_prestige
* has_start_world_choice

**Comment by Marsux** [comment]
So it is ok to do this post release? I would be happy to delay.

Also what do you mean by "Using designated initializers, fields set to FALSE can be omitted." ?

**Comment by bnordli** [comment]
Yes, this is just a reminder to do it at some time.

See http://gcc.gnu.org/onlinedocs//gcc/Designated-Inits.html. Using this, only BOW would need to mention the prestige flag (say).
