### ISSUE TITLE
The Brink of War Search: Should Display the Kept Card Visually, Not Just Buried In Log

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#31]
It's very strange that the only way to see what someone kept during a Search is to scour the log for it.

**Comment by bnordli** [comment]
Then the client must manually parse messages from the engine/server, watching out for results from Search, extracting the card name. I am not fond of doing this.

The search result is already highlighted in the log (using prestige color), and a mouseover will display the card. Isn't that enough?

(I have replayed some of your streaming, you play with a very small message window, wouldn't increasing it a little solve this problem?)

**Comment by dsnvwlmnt** [comment]
Not sure why why the client would have to parse messages. It could be displayed as part of the UI like any tableau card (the client presumably doesn't have to do any log parsing to display tableau cards...). Say overlaying part of the Searching player's play area temporarily. I realize that it would entail new code and likely isn't trivial.

I don't think the log is enough, which is why i brought it up. :)

I actually brought this up for my opponents, not for me. I always check the log to see what people kept on Search and in fact scroll through all the other discards from the Search. My opponents, however, and the average Keldon player, are not typically as observant and that's who this suggestion is targeted at.

The tiny log size is intended, to maximise visibility of the most important thing - cards, which are often quite small, especially in 5p. The zoomed in card is essential, especially if i want to attract people who have never played RFTG.

**Comment by bnordli** [comment]
The game state (as kept internally or sent from the server) does not include the most recent found search card.

Why display the card in the tableau when it already is in a player's hand? And what about all the other revealed cards? Should those be displayed too (potentially tens of cards)? I think the log is the correct place for information that is vital to the game, for people to scroll through when needed.

(I understand your choice to maximize the card, it is a nice visual attraction.)

**Comment by dsnvwlmnt** [comment]
It is self-evident that the selected card should be visually displayed to the opponents, not hidden in a log. I don't know what else to say. :P
