### ISSUE TITLE
Link Binaries on the Release Page?

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#34]
I use other github repositories and the release page always includes binaries, so that everything can be found in one place. I find it a bit odd (and awkward, when wanting to link the install to other people) that it's not in this case...

**Comment by bnordli** [comment]
Good idea. I haven't used that feature before. Does this look good?

**Comment by dsnvwlmnt** [comment]
Yup, perfect!

**Comment by dsnvwlmnt** [comment]
Actually, if u can label it Windows Installer in future that might be better. I don't know how familiar with unlabelled .msi the average person is.

**Comment by joeskeen** [comment]
It would also be nice to include the OS X version on the releases page as well, just like Keldon did at http://keldon.net/rftg/

**Comment by bnordli** [comment]
Except I don't have an OS X version, or the ability to build one..

**Comment by joeskeen** [comment]
If I am able to build it on my machine, could I get it to you somehow to post it?

**Comment by bnordli** [comment]
It would be great to get a pull request with build files for OS X (under build/osx) and some instructions (if they are non-trivial). And if it cannot be built on Windows or Linux, host your binaries anywhere, and I will add them to the release page.

**Comment by bnordli** [comment]
Moving this issue to #39.
