### ISSUE TITLE
Select One Card In Hand - If You Select Another, Unselect The First

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#36]
Something that would be nice to have is when you are prompted to do something with 1 card from hand, if you select one, then select another, instead of now having 2 things selected, it should unselect the previous thing you had selected.

This could be applied to larger numbers as well, with a FIFO style, but mainly the issue stands out when you have to choose 1 card. During explore, payment, discard for vp chips, end of turn overflow, etc.

Examples:

1) Discard for VP chips:
Game state: http://imgur.com/ypxZVaA
Save game: http://pastebin.com/vG4RCMWV

2) End of turn overflow:
Game state: http://imgur.com/a/KOX60
Save game: http://pastebin.com/0QEAM4Cy

**Comment by bnordli** [comment]
This is fairly easy (at least for 1 card) and should be doable.
