### ISSUE TITLE
Alien Weapon Cache Discard Yellow Good for +3 Against Xenos "Payment Cost"

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#37]
GUI payment cost (GUI Options: Display costs during placement - ON) to play the 9/9 Xeno Forward Command here is just empty brackets. **()**

6 base military + 3 against Xenos = 9.

http://imgur.com/a/CGNaY

**Comment by bnordli** [comment]
The "Extra military needed to place: X" text is also missing from the tool tip before placing the world. They don't take temporary military against xenos into account.
