### ISSUE TITLE
Slightly Offset Active Player's Second Tableau Row

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#38]
This is something glaringly obvious to fresh eyes, but becomes completely invisible to regular users. Overlapping cards on the second row should not be 100% perfectly aligned to the first row into some kind of ladder/tower.

They should be offset by at least 5 pixels or something, so that people unfamiliar with the game don't have their eyes glaze over trying to understand what they are looking at. It's cards in play, and they should be clearly separate/offset.

http://imgur.com/a/NAVEK

**Comment by bnordli** [comment]
Why only active player's tableau?

![bilde](https://cloud.githubusercontent.com/assets/5574761/21041888/48461e00-bdee-11e6-8a47-3df903ca323f.png)

**Comment by dsnvwlmnt** [comment]
Oh, maybe because i play mostly larger games, i didn't notice there can be the same overlap for opponents in smaller games.

**Comment by bnordli** [comment]
Also added 1px grey border around all cards, to avoid the large black area composed of overlapping card margins.
