### ISSUE TITLE
Hovering XI Cards In Chat Log - Some Don't Register/Show

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#40]
I noticed that some Xeno Invasion cards don't show their picture in the top left when hovering over their name in the game log. Nothing happens. Examples:

Non-functional:
* Corrosive Uplift World
* Rebel Bunker

Functional:
* Terraforming Defenders
* Galactic Clearing House
* Galactic Home Front

**Comment by Marsux** [comment]
I do not have such issues

![corrosive](https://cloud.githubusercontent.com/assets/22508644/21286010/a94cf2ae-c448-11e6-84dc-d555543fd72a.png)

Could you be more specific, eg by attaching a capture so we can determine what triggers this behaviour?

**Comment by dsnvwlmnt** [comment]
Windows 10 Home. It happened on stream, you can watch starting [from here](https://www.twitch.tv/unsane/v/107347576?t=125m10s).

At 2:05:23, after i hove Terraformed World, you can see that Starry Rift Pioneers does not register.
At 2:05:28, Public Works works, but Corrosive Uplift World does not register. This is where i notice the bug.
At 2:06:25: Rebel Bunker does not register.
At 2:06:34: Terraforming Defenders **does** register!

**Comment by Marsux** [comment]
Ok, ignore my last comment, I wasn't aware that you could get to the zoomed card by howering in the chat log and misread the issue.

**Comment by bnordli** [comment]
I haven't watched the stream yet, but I suspect this is due to the technical limitation that there can be only one card displayed per log message. If there are multiple cards listed in one message (for instance during consume), the card with the lowest id gets priority.

**Comment by dsnvwlmnt** [comment]
Strange that that would have never occurred for me until XI...

**Comment by bnordli** [comment]
After watching the stream, I can confirm that this is what is happening: In the first example, Terraformed World takes precedence over Starry Rift Pioneers. In the second example. Public Works takes precedence over Corrosive Uplift World.
