### ISSUE TITLE
Request: Zipped version of new release 

### ISSUE THREAD

**Issue by gchambers419** [bnordli/rftg#44]
I'm running the app on a very old version of Wine on a very old version of Linux. The Wine install doesn't support MSI files.  I was able to run the previous release from the ZIP file without issues. Is it possible to create a ZIP release?

**Comment by bnordli** [comment]
A standalone zip file is now added to https://github.com/bnordli/rftg/releases/tag/0.9.5 :)

**Comment by gchambers419** [comment]
Sweet. Thanks for the fast response.
