### ISSUE TITLE
Greatest Infrastructure goal doesn't take into account development discarding breaking ties

### ISSUE THREAD

**Issue by dominiquelee** [bnordli/rftg#56]
In a 2PA game, the two players are tied for greatest infrastructure (with both 6 devs) immediately before a Settle phase. During the Settle phase, the Blue player discards Rebel Sneak Attack to place an additional world, thus breaking the tie. His opponent, the Red player is now leading the goal race, but still only has 3 points and no possession of the goal token.
The token was then awarded to the Red player after the next Development phase, where both players played a new development.
![image](https://user-images.githubusercontent.com/1204726/77852676-312f0700-71e0-11ea-82c0-c99797bc9b2f.png)

**Comment by bnordli** [comment]
This is correct behavior according to the rules:
The "most" goals can only be *claimed* at the end of the phase(s) listed on the goal. They can be lost at any time though.

If this was the last round of the game, Red would only score 3 points for this goal. If the game continued, he would claim it atthe end of the next develop phase (if he still is in the lead.)
