### ISSUE TITLE
"Passed card without good!" error immediately after action selection

### ISSUE THREAD

**Issue by dominiquelee** [bnordli/rftg#60]
In the situation below, any chosen actions lead to a "Passed card without good!" error that kills the app. As far as I can tell, we don't even reach the Consume phase, it happens before the Explore phase even begins.
![image](https://user-images.githubusercontent.com/1204726/131325398-4bb84d89-9898-4da2-98d3-d0a5f58a2394.png)
[passedcardwithoutgood.xml.txt](https://github.com/bnordli/rftg/files/7075989/passedcardwithoutgood.xml.txt)

**Comment by bnordli** [comment]
This is a known bug that was fixed by commit 6624f60b05, in the (not yet released) 0.9.6 version.
