### ISSUE TITLE
Implementing the 5 card changes from the second edition

### ISSUE THREAD

**Issue by JimWestergren** [bnordli/rftg#61]
Please could it be possible to have the cards updated according to the second edition that was released in 2018?
Info here https://boardgamegeek.com/thread/1969131/huh-was-not-aware-race-2e-will-include-adjusted-ca

Thanks in advance.

**Comment by bnordli** [comment]
No sorry, I don't expect to receive the updated artworks from the publisher.
(If you really want to play with them, you can try to edit the card rules in `cards.txt`.)

**Comment by JimWestergren** [comment]
Ok, thank you Børge. I understand you probably then also need a new legal permission for those etc.
No worry, thanks!
