### ISSUE TITLE
Improved logistics and doomed world in advanced mode

### ISSUE THREAD

**Issue by rivten** [bnordli/rftg#62]
Hello there !

First of all, thanks for the software. We have a lot of fun with it.

I wanted to report an issue that happened in one of our game today. My opponent had `Improved Logistics` already on his board, so he could settle twice on one settle phase. Not necessarily relevant but we were playing in advanced mode.
On the settle phase, he settled `Doomed World` which allows him to discard this world to play another non-alien world without paying its cost.
Then he has the opportunity to trigger the effect of `Improved Logistics` to place a second. He wish to settle a non-alien world (it was a green world, non-military). But, when he accept to use his second settle power, the UI did not allow him to settle this card through the usage of `Doomed World`, even though he could have used `Doomed World` which he just settled. It forced him to discard his hand to pay the cost.

I think this is a bug.

I am not familiar with the codebase but I had a very quick look. I wonder if [this code](https://github.com/bnordli/rftg/blob/master/src/engine.c#L6670) does not mark `Doomed World`'s power as used, thus making him unable to use it.

**Comment by bnordli** [comment]
This is correct according to the rules. Base game, p4:
> Powers first take effect in the phase _after_ their card is placed.

So Doomed World cannot be sacrificed the phase it was played in order to place a second world (via Improved Logistics).

(When playing the 2P Advanced game, it _can_ however be placed in the first Settle phase and sacrificed in the second Settle phase the same round.)

**Comment by rivten** [comment]
I had no idea ! Thanks for taking the time to answer me and sorry for the wrong bug report.

Have a nice day !!
