### ISSUE TITLE
Trade League Bad UI Wording

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#7]
Trade League's UI wording is no good and misleading. The drop down says "Trade good", and then once you've ok'd that, the UI says "Choose good to trade". You're technically **not** trading nor selling a good, you're using a **consume** power to "discard a good to draw cards equal..."

**Comment by bnordli** [comment]
In theory I agree, but the text has always been like this, and for all practical purposes, except Alien Fuel Refinery from AA, there are no practical differences. Also, Trade League and BMTW are implemented internally exactly as a trade, so I would say the work needed to change this is not worth it.

**Comment by dsnvwlmnt** [comment]
ok

**Comment by Marsux** [comment]
This is not exactly true: the Trade League power can be activated for world where selling is not an option, eg Oort Cloud. So technically there is a difference between "trade good" and "consume for trade".

**Comment by dsnvwlmnt** [comment]
Yes, i think we all agree on that.

**Comment by bnordli** [comment]
Yes, I meant to add AOCR along with the Fuel Refinery above, but the program handles these cards correctly, so the problem only relates to the text in the GUI. Closing this, but I won't oppose a fix if anyone cares to take ownership.
